import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { useNavigate, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import toast from 'react-hot-toast';
import { KeyRound, ShieldCheck, Activity, HeartPulse, Stethoscope, ArrowRight } from 'lucide-react';
import Button from '../../components/common/Button';
import Logo from '../../components/common/Logo';
import { PATHS } from '../../constants/routes';
import { useAuth } from '../../contexts/AuthContext';

const FLOATERS = [
  { Icon: HeartPulse, top: '14%', left: '18%', delay: 0 },
  { Icon: Stethoscope, top: '62%', left: '10%', delay: 0.5 },
  { Icon: ShieldCheck, top: '78%', left: '68%', delay: 1 },
  { Icon: Activity, top: '22%', left: '72%', delay: 1.4 },
];

// Step 1 of the Healthcare Worker registration flow. A Staff Access
// Code — generated by an Admin (see AccessCodeManagement.jsx) — is
// verified here; the role it grants is never chosen by the worker.
// Once verified, we hand the role + code to Register via router
// state, which then shows the correct staff registration form.
export default function StaffAccessCode() {
  const navigate = useNavigate();
  const { checkStaffAccessCode, isLoading } = useAuth();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({ defaultValues: { code: '' } });

  const onSubmit = async ({ code }) => {
    const result = await checkStaffAccessCode(code.trim());
    if (result.success) {
      toast.success('Access code verified.');
      navigate(PATHS.REGISTER, { state: { staffRole: result.role, staffCode: result.code }, replace: true });
    } else {
      toast.error(result.error || 'Invalid staff access code.');
    }
  };

  return (
    <div className="grid min-h-screen lg:grid-cols-2">
      {/* Left — illustration, matches Login/Register */}
      <div className="relative hidden overflow-hidden bg-gradient-to-br from-brand-600 via-brand-700 to-brand-900 lg:flex lg:flex-col lg:justify-between lg:p-12">
        <div className="pointer-events-none absolute inset-0" aria-hidden="true">
          {FLOATERS.map(({ Icon, top, left, delay }, i) => (
            <motion.span
              key={i}
              className="absolute text-white/15"
              style={{ top, left }}
              animate={{ y: [0, -16, 0] }}
              transition={{ duration: 5 + i, repeat: Infinity, ease: 'easeInOut', delay }}
            >
              <Icon size={40} />
            </motion.span>
          ))}
          <div className="absolute -left-24 -top-24 h-72 w-72 rounded-full bg-white/10 blur-3xl" />
          <div className="absolute -bottom-24 -right-16 h-80 w-80 rounded-full bg-black/10 blur-3xl" />
        </div>

        <Link to={PATHS.HOME} className="relative z-10">
          <Logo variant="light" />
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="relative z-10"
        >
          <h2 className="font-display text-3xl font-semibold leading-snug text-white">
            Healthcare Worker onboarding
          </h2>
          <p className="mt-3 max-w-md text-sm text-brand-50/80">
            ASHA Workers, Health Officers, and Pharmacists register with an Admin-issued Staff
            Access Code. It determines your role automatically — no need to select one yourself.
          </p>
        </motion.div>

        <p className="relative z-10 text-xs text-brand-50/60">
          © {new Date().getFullYear()} HealthGuard AI — demo build, frontend-only auth.
        </p>
      </div>

      {/* Right — access code form */}
      <div className="flex items-center justify-center bg-aurora bg-dot-grid px-4 py-12 sm:px-6">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="glass-panel w-full max-w-md p-8 sm:p-10"
        >
          <div className="flex justify-center lg:hidden">
            <Logo />
          </div>

          <div className="mt-6 flex justify-center lg:mt-0">
            <span className="flex h-12 w-12 items-center justify-center rounded-xl bg-brand-100 text-brand-600 dark:bg-brand-500/10 dark:text-brand-400">
              <KeyRound className="h-6 w-6" aria-hidden="true" />
            </span>
          </div>

          <h1 className="mt-4 text-center font-display text-xl font-semibold text-slate-900 dark:text-white">
            Enter your Staff Access Code
          </h1>
          <p className="mt-1 text-center text-sm text-slate-500 dark:text-slate-400">
            Issued by your Admin. This determines your role — ASHA Worker, Health Officer, or
            Pharmacist — automatically.
          </p>

          <form onSubmit={handleSubmit(onSubmit)} className="mt-8 space-y-4" noValidate>
            <div>
              <label htmlFor="code" className="label-text">Staff Access Code</label>
              <div className="relative">
                <KeyRound className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                <input
                  id="code"
                  type="text"
                  autoCapitalize="characters"
                  placeholder="ASHA-DEMO"
                  className="input-field pl-10 tracking-widest"
                  {...register('code', { required: 'Staff access code is required' })}
                />
              </div>
              {errors.code && <p className="mt-1.5 text-xs text-signal-rose">{errors.code.message}</p>}
            </div>

            <Button type="submit" variant="primary" isLoading={isLoading} className="w-full">
              {!isLoading && (<>Verify code <ArrowRight className="h-4 w-4" /></>)}
              {isLoading && 'Verifying…'}
            </Button>
          </form>

          <p className="mt-6 text-center text-sm text-slate-500 dark:text-slate-400">
            Not a healthcare worker?{' '}
            <Link to={PATHS.REGISTER} className="font-medium text-brand-600 hover:text-brand-700 dark:text-brand-400">
              Register as a Citizen
            </Link>
          </p>

          <p className="mt-4 text-center text-sm text-slate-500 dark:text-slate-400">
            Already have an account?{' '}
            <Link to={PATHS.LOGIN} className="font-medium text-brand-600 hover:text-brand-700 dark:text-brand-400">
              Login
            </Link>
          </p>
        </motion.div>
      </div>
    </div>
  );
}
