ALTER TABLE health_officers ADD COLUMN IF NOT EXISTS village VARCHAR(100);
ALTER TABLE health_officers ADD COLUMN IF NOT EXISTS district VARCHAR(100);
ALTER TABLE pharmacists ADD COLUMN IF NOT EXISTS village VARCHAR(100);
ALTER TABLE pharmacists ADD COLUMN IF NOT EXISTS district VARCHAR(100);
