// Central path registry. Keeps route strings out of magic literals
// scattered across pages/components.
export const PATHS = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  PENDING_APPROVAL: '/pending-approval',
  COMPLETE_PROFILE: '/complete-profile',
  ONBOARDING: '/onboarding',
  UNAUTHORIZED: '/unauthorized',
  SERVER_ERROR: '/server-error',
  NOT_FOUND: '*',

  CITIZEN: '/citizen',
  CITIZEN_MY_PROFILE: '/profile',
  CITIZEN_HEALTH_SCORE: '/citizen/health-score',
  CITIZEN_SYMPTOM_CHECKER: '/citizen/symptom-checker',
  CITIZEN_CHAT: '/citizen/chat',
  CITIZEN_DISEASES: '/citizen/diseases',
  CITIZEN_HOSPITALS: '/citizen/hospitals',
  CITIZEN_MEDICINES: '/citizen/medicines',
  CITIZEN_EMERGENCY: '/citizen/emergency',
  CITIZEN_SCHEMES: '/citizen/schemes',
  CITIZEN_ANALYTICS: '/citizen/nutrition-planner',
  CITIZEN_NUTRITION_PLANNER: '/citizen/nutrition-planner',
  ASHA: '/asha',
  ASHA_ASSIGNED_CITIZENS: '/asha/assigned-citizens',
  ASHA_FAMILIES: '/asha/families',
  ASHA_VISITS: '/asha/visits',
  ASHA_CHILD_HEALTH: '/asha/child-health',
  ASHA_SURVEILLANCE: '/asha/surveillance',
  ASHA_ASSISTANT: '/asha/assistant',
  ASHA_REPORTS: '/asha/reports',
  PHARMACIST: '/pharmacist',
  PHARMACIST_INVENTORY: '/pharmacist/inventory',
  PHARMACIST_FORECASTING: '/pharmacist/forecasting',
  PHARMACIST_STOCK_ALERTS: '/pharmacist/stock-alerts',
  PHARMACIST_ORDERS: '/pharmacist/orders',
  PHARMACIST_ANALYTICS: '/pharmacist/analytics',
  PHARMACIST_REPORTS: '/pharmacist/reports',
  PHARMACIST_NOTIFICATIONS: '/pharmacist/notifications',
  OFFICER: '/officer',
  OFFICER_ANALYTICS: '/officer/analytics',
  OFFICER_DISEASE_MONITORING: '/officer/disease-monitoring',
  OFFICER_HEALTH_MAP: '/officer/health-map',
  OFFICER_REFERRALS: '/officer/referrals',
  OFFICER_REFERRAL_MONITORING: '/officer/referral-monitoring',
  OFFICER_VACCINATION: '/officer/vaccination',
  OFFICER_CAMPAIGNS: '/officer/campaigns',
  OFFICER_EMERGENCY: '/officer/emergency',
  OFFICER_AI_INSIGHTS: '/officer/ai-insights',
  OFFICER_BROADCAST: '/health-officer/broadcast',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_CITIZEN_ASSIGNMENTS: '/admin/citizen-assignments',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_CAMPAIGNS: '/admin/campaigns',
  ADMIN_SYSTEM: '/admin/system',
  ADMIN_NOTIFICATIONS: '/admin/notifications',

  CHANGE_PASSWORD: '/change-password',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
};
