package com.healthguard.citizen.enums;

public enum NotificationType {
    MEDICINE_REMINDER,
    VACCINATION_REMINDER,
    HEALTH_ALERT,
    CAMPAIGN,
    EMERGENCY,
    SYSTEM,
    AI_FOLLOWUP,
    HEALTH_OFFICER_BROADCAST,
    CITIZEN_ASSIGNMENT,
    HOME_VISIT,
    DISEASE_SURVEILLANCE,
    CHILD_HEALTH,
    REFERRAL,
    DISEASE_ALERT,
    LOW_STOCK,
    OUT_OF_STOCK,
    EXPIRY_ALERT,
    PROCUREMENT_APPROVED
}
