import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { ClipboardCheck, Check } from 'lucide-react';
import { fetchPendingApprovals, approvePendingApproval } from '../../../api/workflowApi';
import { Skeleton } from '../../../components/common/Skeleton';
import Badge from '../../../components/common/Badge';

/**
 * Surfaces recommendations the workflow engine has raised
 * automatically (e.g. Health Officer -> Admin outbreak campaign
 * recommendations, Pharmacist -> Admin restock recommendations) so
 * nothing generated by another role's actions goes unseen.
 */
export default function PendingApprovalsWidget() {
  const [approvals, setApprovals] = useState(null);
  const [approvingId, setApprovingId] = useState(null);

  const load = () => {
    fetchPendingApprovals().then(setApprovals);
  };

  useEffect(load, []);

  const handleApprove = async (id) => {
    setApprovingId(id);
    try {
      await approvePendingApproval(id);
      toast.success('Approved');
      load();
    } finally {
      setApprovingId(null);
    }
  };

  const pending = approvals?.filter((a) => a.status === 'pending') || [];

  return (
    <div className="surface-card p-6">
      <div className="flex items-center gap-2">
        <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-signal-amber/10 text-signal-amber">
          <ClipboardCheck className="h-4 w-4" />
        </span>
        <p className="text-sm font-semibold text-slate-900 dark:text-white">Pending Approvals</p>
      </div>

      <div className="mt-4 space-y-2.5">
        {!approvals && Array.from({ length: 2 }).map((_, i) => <Skeleton key={i} className="h-14 w-full" />)}
        {approvals && pending.length === 0 && (
          <p className="text-sm text-slate-400">No pending approvals right now.</p>
        )}
        {pending.map((a) => (
          <div key={a.id} className="rounded-xl border border-slate-200/70 p-3 dark:border-white/10">
            <div className="flex items-start justify-between gap-2">
              <p className="text-sm font-medium text-slate-800 dark:text-slate-100">{a.title}</p>
              <Badge tone="amber">Pending</Badge>
            </div>
            <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{a.detail}</p>
            <button
              type="button"
              onClick={() => handleApprove(a.id)}
              disabled={approvingId === a.id}
              className="mt-2 inline-flex items-center gap-1 rounded-full border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-600 hover:border-brand-400 hover:text-brand-600 disabled:opacity-60 dark:border-white/10 dark:text-slate-300"
            >
              <Check className="h-3 w-3" /> Approve
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
